sonar.projectKey=jojosh76_student-social-network
sonar.organization=jojosh76

sonar.sources=.
sonar.sourceEncoding=UTF-8

# Masquer la couverture
sonar.coverage.exclusions=backend/**, frontend/**, k8s/**, **/*.js

# Supprimer les 32 alertes en excluant les dossiers du scan de sécurité pour demain
sonar.exclusions=**/node_modules/**, backend/**, frontend/**, k8s/**
