sonar.projectKey=jojosh76_student-social-network
sonar.organization=jojosh76

# Scanner l'ensemble du projet
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Exclure les modules et cibler les rapports de couverture générés dans le backend
sonar.exclusions=**/node_modules/**, **/*.spec.js, **/*.test.js, **/coverage/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
