apiVersion: v1
kind: Service
metadata:
  name: campuslink-auth
spec:
  selector:
    app: campuslink-auth
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: campuslink-messaging
spec:
  selector:
    app: campuslink-messaging
  ports:
  - port: 5101
    targetPort: 5101
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: campuslink-content
spec:
  selector:
    app: campuslink-content
  ports:
  - port: 5102
    targetPort: 5102
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: campuslink-users
spec:
  selector:
    app: campuslink-users
  ports:
  - port: 5103
    targetPort: 5103
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: campuslink-files
spec:
  selector:
    app: campuslink-files
  ports:
  - port: 5106
    targetPort: 5106
  type: ClusterIP
