name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 1. On va dans backend pour installer express et jest
      - name: Install dependencies
        run: |
          cd backend
          npm install

      # 2. On va dans backend pour lancer le test et générer le dossier coverage
      - name: Run all tests with coverage
        run: |
          cd backend
          npm test -- --coverage --watchAll=false

      # 3. Scan SonarQube
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
